name: materikas_landing_page
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  # youtube_player_flutter: ^9.1.1
  google_fonts: ^5.0.0
  carousel_slider: ^5.0.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  url_launcher: ^6.3.1
  http: ^1.2.2
  # flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
